#! /bin/bash

#########################################################
## PBS script to run 2D Spectroscopy in parallel on multiple cores 
##
## @author: Wei Xu
## @affiliation: CSC@BNL
## @date created: Jul. 20, 2013
## @date last modified: Jul. 20, 2013
#########################################################

#PBS -S /bin/bash
#PBS -l nodes=8:ppn=32
##PBS -j oe
#PBS -N X8C
#PBS -o ${PBS_JOBID}.out
#PBS -e ${PBS_JOBID}.err
##PBS -M xuw@bnl.gov

# Print date and time
date

let i=8*32

cd /kbase/home/wxu/WorkflowPrototype/Parallel_Packages/X8C

#/software/mpich2/1.4.1p1/bin/mpirun -np $i /kbase/home/wxu/WorkflowPrototype/Parallel_Packages/X8C/preprocess.py

#date

#/software/mpich2/1.4.1p1/bin/mpirun -np $i /kbase/home/wxu/WorkflowPrototype/Parallel_Packages/X8C/LSF.py

/software/mpich2/1.4.1p1/bin/mpirun -np $i /kbase/home/wxu/WorkflowPrototype/Parallel_Packages/X8C/spectroscopy.py


date

python /kbase/home/wxu/WorkflowPrototype/Parallel_Packages/X8C/merge_LSF.py ${outfile}

# Print date and time again
date
